#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import main_builders

env.main_sources = []

env.add_source_files(env.main_sources, "*.cpp")

lib = env.add_library("main", env.main_sources)
env.Prepend(LIBS=[lib])
